spring:
  application:
    name: hering-challenge
  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/desafio_db
    username: root
    password: root
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 1000
      connection-test-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  # Liquibase
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hering_tts_challenge
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer